language: node_js
node_js: "12"
cache: npm

before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  - in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa

install:
  - git clone https://github.com/shahar603/digitalocean-party.git
  - cd digitalocean-party
  - npm install

after_success:
  - bash ./deploy.sh